FROM node:22

# Устанавливаем bash и любые утилиты по желанию
RUN apt-get update && apt-get install -y nano git

# Устанавливаем рабочую директорию
WORKDIR /workspace

# Открываем терминал по запуску
CMD [ "bash" ]
